version: '3.9'

services:
  share-data-webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "5170:5170"

    image: bluewhale3004/data-share-project:aws-latest  # Specify the image name and tag
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
  
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # remember to grant privilege to this file chmod 644 init.sql


volumes:
  mysql-data:
